export const characterResponse = {
  characters: [
    {
      skills: {
        power: 4,
        health: 3,
        mobility: 3,
        technical: 2,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f62000",
      name: "Ryu",
      __v: 0,
    },
    {
      skills: {
        power: 2,
        health: 2,
        mobility: 4,
        technical: 4,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62001",
      name: "Chun-li",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 4,
        technical: 3,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62002",
      name: "Nash",
      __v: 0,
    },
    {
      skills: {
        power: 5,
        health: 3,
        mobility: 4,
        technical: 4,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62003",
      name: "M.Bison(Dictator)",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 5,
        technical: 2,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62004",
      name: "Cammy",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 4,
        mobility: 1,
        technical: 3,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f62005",
      name: "Birdie",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 4,
        technical: 2,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62006",
      name: "Ken",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 5,
        technical: 3,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62007",
      name: "Vega",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 2,
        technical: 4,
        scope: 1,
      },
      _id: "5fd4be5bd99c4a2077f62008",
      name: "R.Mika",
      __v: 0,
    },
    {
      skills: {
        power: 2,
        health: 3,
        mobility: 4,
        technical: 3,
        scope: 2,
      },
      _id: "5fd4be5bd99c4a2077f62009",
      name: "Rashid",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 4,
        technical: 5,
        scope: 2,
      },
      _id: "5fd4be5bd99c4a2077f6200a",
      name: "Karin",
      __v: 0,
    },
    {
      skills: {
        power: 5,
        health: 5,
        mobility: 1,
        technical: 2,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f6200b",
      name: "Zangief",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 4,
        technical: 3,
        scope: 1,
      },
      _id: "5fd4be5bd99c4a2077f6200c",
      name: "Laura",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 1,
        technical: 3,
        scope: 5,
      },
      _id: "5fd4be5bd99c4a2077f6200d",
      name: "Dhalsim",
      __v: 0,
    },
    {
      skills: {
        power: 2,
        health: 3,
        mobility: 3,
        technical: 3,
        scope: 5,
      },
      _id: "5fd4be5bd99c4a2077f6200e",
      name: "F.A.N.G",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 4,
        mobility: 2,
        technical: 3,
        scope: 2,
      },
      _id: "5fd4be5bd99c4a2077f6200f",
      name: "Alex",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 3,
        mobility: 3,
        technical: 2,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f62010",
      name: "Guile",
      __v: 0,
    },
    {
      skills: {
        power: 2,
        health: 2,
        mobility: 4,
        technical: 3,
        scope: 2,
      },
      _id: "5fd4be5bd99c4a2077f62011",
      name: "Ibuki",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 4,
        mobility: 3,
        technical: 3,
        scope: 2,
      },
      _id: "5fd4be5bd99c4a2077f62012",
      name: "Balrog",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 5,
        technical: 2,
        scope: 2,
      },
      _id: "5fd4be5bd99c4a2077f62013",
      name: "Juri",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 4,
        mobility: 4,
        technical: 3,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62014",
      name: "Urien",
      __v: 0,
    },
    {
      skills: {
        power: 5,
        health: 3,
        mobility: 4,
        technical: 5,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62015",
      name: "Akuma",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 2,
        mobility: 5,
        technical: 2,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62016",
      name: "Kolin",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 4,
        technical: 3,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62017",
      name: "Ed",
      __v: 0,
    },
    {
      skills: {
        power: 5,
        health: 5,
        mobility: 1,
        technical: 4,
        scope: 5,
      },
      _id: "5fd4be5bd99c4a2077f62018",
      name: "Abigail",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 2,
        technical: 3,
        scope: 5,
      },
      _id: "5fd4be5bd99c4a2077f62019",
      name: "Menat",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 3,
        mobility: 4,
        technical: 5,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f6201a",
      name: "Zeku",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 3,
        technical: 4,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f6201b",
      name: "Sakura",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 5,
        technical: 3,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f6201c",
      name: "Blanka",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 2,
        technical: 4,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f6201d",
      name: "Falke",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 3,
        technical: 5,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f6201e",
      name: "Cody",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 3,
        technical: 5,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f6201f",
      name: "G",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 3,
        mobility: 2,
        technical: 4,
        scope: 5,
      },
      _id: "5fd4be5bd99c4a2077f62020",
      name: "Sagat",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 2,
        mobility: 4,
        technical: 4,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62021",
      name: "Kage",
      __v: 0,
    },
    {
      skills: {
        power: 4,
        health: 4,
        mobility: 3,
        technical: 2,
        scope: 2,
      },
      _id: "5fd4be5bd99c4a2077f62022",
      name: "E.Honda",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 2,
        mobility: 4,
        technical: 3,
        scope: 3,
      },
      _id: "5fd4be5bd99c4a2077f62023",
      name: "Lucia",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 2,
        technical: 2,
        scope: 5,
      },
      _id: "5fd4be5bd99c4a2077f62024",
      name: "Poison",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 2,
        technical: 5,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f62025",
      name: "Gill",
      __v: 0,
    },
    {
      skills: {
        power: 3,
        health: 3,
        mobility: 2,
        technical: 5,
        scope: 4,
      },
      _id: "5fd4be5bd99c4a2077f62026",
      name: "Seth",
      __v: 0,
    },
  ],
};
