export const actionTypes = {
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  FETCH_USER: "FETCH_USER",
  LOGOUT: "LOGOUT",
  FETCH_CHARACTERS: "FETCH_CHARACTERS",
  SET_CHARACTERS: "SET_CHARACTERS",
  ADD_CHARACTER: "ADD_CHARACTER",
  GET_NOTES: "GET_NOTES",
  ADD_NOTE: "ADD_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  FETCH_FAILURE: "FETCH_FAILURE",
};
